#!/usr/bin/env bash
# Bundle ./data into a single zip (excluding the raw .h5 demos and the nested
# .zip archives by default) and upload it to a free host, so the repository
# stays lightweight without Git LFS quotas.
#
#   ./upload_data.sh                       # build data.zip and upload it
#   ./upload_data.sh --no-upload           # only build + verify locally
#   ./upload_data.sh --trim                # ~6.5 GB instead of ~32 GB
#   ./upload_data.sh --list                # show what would be included
#   ./upload_data.sh --backend rclone --remote dropbox:heca-data
#
# Backends:
#   zenodo (default) : curl + ZENODO_TOKEN, returns a public DOI link
#   rclone           : any rclone remote (gdrive:, dropbox:, onedrive:, s3:, ...)
#
# Writes the archive, its sha256 and a file manifest to the repository root
# (all three are git-ignored). A successful upload prints the values to paste
# into data_bundle.env, which is what download_data.sh reads.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# shellcheck source=data_bundle.env
[[ -f data_bundle.env ]] && source ./data_bundle.env

DATA_DIR="${DATA_DIR:-data}"
BUNDLE_ZIP="${BUNDLE_ZIP:-data.zip}"
BUNDLE_EXCLUDES="${BUNDLE_EXCLUDES:-*.h5 *.zip}"
BUNDLE_TRIM_EXCLUDES="${BUNDLE_TRIM_EXCLUDES:-*/old/* */calvin/* *.png}"
BUNDLE_BACKEND="${BUNDLE_BACKEND:-zenodo}"
ZENODO_API="${ZENODO_API:-https://zenodo.org/api}"
RCLONE_REMOTE="${RCLONE_REMOTE:-gdrive:heca-data}"
TITLE="HECA data bundle"
DESCRIPTION="Portable HECA data: fitted conditions, expert policies and network checkpoints. Raw .h5 demos and nested .zip archives are excluded."

DO_UPLOAD=1 TRIM=0 LIST_ONLY=0 FAST=0

usage() { sed -n '2,22p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }
info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }
human() { numfmt --to=iec --suffix=B "$1" 2>/dev/null || echo "$1 bytes"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --data-dir)    DATA_DIR="$2"; shift 2 ;;
    --out)         BUNDLE_ZIP="$2"; shift 2 ;;
    --backend)     BUNDLE_BACKEND="$2"; shift 2 ;;
    --remote)      RCLONE_REMOTE="$2"; shift 2 ;;
    --title)       TITLE="$2"; shift 2 ;;
    --description) DESCRIPTION="$2"; shift 2 ;;
    --no-upload)   DO_UPLOAD=0; shift ;;
    --trim)        TRIM=1; shift ;;
    --list)        LIST_ONLY=1; shift ;;
    --fast)        FAST=1; shift ;;
    -h|--help)     usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

# The sha256 and manifest always sit next to the archive, whatever --out says.
BUNDLE_SHA="${BUNDLE_ZIP}.sha256"
BUNDLE_MANIFEST="${BUNDLE_ZIP}.manifest.txt"

[[ -d "$DATA_DIR" ]] || die "no such directory: $DATA_DIR"
command -v zip >/dev/null || die "zip is required (apt install zip / dnf install zip / brew install zip)"

PARENT="$(cd "$(dirname "$DATA_DIR")" && pwd)"
BASE="$(basename "$DATA_DIR")"

# One matcher decides what is in the bundle; the scan, the listing, the manifest
# and the archive are all derived from it. Patterns are shell globs, so "*"
# matches "/" as well:  *.h5  also drops data/scenes/x/y.h5.
# 'read -a' splits on whitespace *without* pathname expansion: an unquoted
# assignment would glob '*/old/*' against the working directory and silently
# replace the pattern with whatever happens to match.
read -r -a EXCLUDES <<<"$BUNDLE_EXCLUDES"
if [[ $TRIM -eq 1 ]]; then
  read -r -a TRIM_PATTERNS <<<"$BUNDLE_TRIM_EXCLUDES"
  EXCLUDES+=( "${TRIM_PATTERNS[@]}" )
fi

info "scanning '$DATA_DIR' (excluding: ${EXCLUDES[*]})"

# Build the manifest first: it is the single source of truth for what ships.
# (Per-file sha256 over ~260k files would cost more than the upload itself; the
# archive hash below covers integrity.)
manifest_dir="$(dirname "$BUNDLE_MANIFEST")"
[[ -d "$manifest_dir" ]] || mkdir -p "$manifest_dir"
{
  echo "# generated by upload_data.sh on $(date -Iseconds)"
  echo "# excludes: ${EXCLUDES[*]}"
  echo "# columns: bytes<TAB>path"
  find "$PARENT/$BASE" -type f -printf "%s\t$BASE/%P\n" | while IFS=$'\t' read -r size rel; do
    for pat in "${EXCLUDES[@]}"; do
      # shellcheck disable=SC2053
      [[ "$rel" == $pat ]] && continue 2
    done
    printf '%s\t%s\n' "$size" "$rel"
  done
} > "$BUNDLE_MANIFEST"

read -r n_files raw_bytes <<<"$(awk -F'\t' '!/^#/ {n++; s+=$1} END {printf "%d %d", n, s+0}' "$BUNDLE_MANIFEST")"
[[ "${n_files:-0}" -gt 0 ]] || die "nothing to archive in $DATA_DIR with the current excludes"
info "$n_files files, $(human "$raw_bytes") before compression"

if [[ $LIST_ONLY -eq 1 ]]; then
  awk -F'\t' '!/^#/ {printf "%12d  %s\n", $1, $2}' "$BUNDLE_MANIFEST" | sort -rn | head -40
  exit 0
fi

# --- build ----------------------------------------------------------------
rm -f "$BUNDLE_ZIP" "$BUNDLE_SHA"
ZIP_FLAGS=( -q -X )
[[ $FAST -eq 1 ]] && ZIP_FLAGS+=( -1 )
zip_path="$BUNDLE_ZIP"
[[ "$zip_path" != /* ]] && zip_path="$ROOT/$zip_path"
info "writing $BUNDLE_ZIP (reads all of $BASE; expect minutes for a large tree)"
# 'zip -@' takes the names on stdin: listing them as arguments would exceed
# ARG_MAX for this tree (~260k files).
( cd "$PARENT" && awk -F'\t' '!/^#/ {print $2}' "$ROOT/$BUNDLE_MANIFEST" \
  | zip "${ZIP_FLAGS[@]}" "$zip_path" -@ )

info "hashing"
# hash inside the archive's directory so the sidecar is portable next to it
( cd "$(dirname "$BUNDLE_ZIP")" && sha256sum "$(basename "$BUNDLE_ZIP")" > "$(basename "$BUNDLE_SHA")" )

zip_bytes=$(stat -c '%s' "$BUNDLE_ZIP")
entries=$(unzip -l "$BUNDLE_ZIP" 2>/dev/null | tail -1 | awk '{print $2}')
info "archive: $(human "$zip_bytes"), $entries entries"
info "sha256 : $(cut -d' ' -f1 < "$BUNDLE_SHA")"
info "manifest: $BUNDLE_MANIFEST ($(awk '!/^#/' "$BUNDLE_MANIFEST" | wc -l) files)"

if [[ $DO_UPLOAD -eq 0 ]]; then
  info "--no-upload given, stopping here"
  exit 0
fi

# --- upload ---------------------------------------------------------------
case "$BUNDLE_BACKEND" in
  zenodo)
    [[ -n "${ZENODO_TOKEN:-}" ]] || die "ZENODO_TOKEN is not set; create one with deposit:write + deposit:actions at https://zenodo.org/account/settings/applications/tokens/new/"
    command -v curl >/dev/null || die "curl is required for the zenodo backend"
    command -v python3 >/dev/null || die "python3 is required for the zenodo backend"

    info "creating Zenodo deposition on $ZENODO_API"
    meta=$(python3 -c '
import json, sys
print(json.dumps({"metadata": {
    "title": sys.argv[1],
    "upload_type": "dataset",
    "description": sys.argv[2],
    "creators": [{"name": "HECA maintainers"}],
    "access_right": "open",
    "license": "cc-by-4.0",
}}))' "$TITLE" "$DESCRIPTION")

    resp=$(curl -sS -H "Authorization: Bearer $ZENODO_TOKEN" \
      -H "Content-Type: application/json" -d "$meta" "$ZENODO_API/deposit/depositions") \
      || die "deposition request failed"
    dep_id=$(python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])' <<<"$resp") \
      || die "unexpected Zenodo response: $resp"
    bucket=$(python3 -c 'import json,sys; print(json.load(sys.stdin)["links"]["bucket"])' <<<"$resp")
    info "deposition $dep_id, uploading $(basename "$BUNDLE_ZIP")"

    curl -sS --fail -H "Authorization: Bearer $ZENODO_TOKEN" \
      --upload-file "$BUNDLE_ZIP" "$bucket/$(basename "$BUNDLE_ZIP")" >/dev/null \
      || die "zip upload failed"
    curl -sS --fail -H "Authorization: Bearer $ZENODO_TOKEN" \
      --upload-file "$BUNDLE_SHA" "$bucket/$(basename "$BUNDLE_SHA")" >/dev/null \
      || die "sha256 upload failed"

    info "publishing (this is what makes the link permanent)"
    curl -sS --fail -X POST -H "Authorization: Bearer $ZENODO_TOKEN" \
      "$ZENODO_API/deposit/depositions/$dep_id/actions/publish" >/dev/null \
      || die "publish failed; the draft is kept at https://zenodo.org/deposit/$dep_id"

    file_url=$(python3 -c '
import json, sys, urllib.request
api, rid = sys.argv[1], sys.argv[2]
with urllib.request.urlopen(f"{api}/records/{rid}") as fh:
    rec = json.load(fh)
print(next((f["links"]["self"] for f in rec.get("files", []) if f["key"].endswith(".zip")), ""))
' "$ZENODO_API" "$dep_id")

    echo
    info "published: https://zenodo.org/records/$dep_id"
    cat <<EOF

Paste these into data_bundle.env so a fresh clone can fetch the data:

    BUNDLE_BACKEND="zenodo"
    ZENODO_RECORD="$dep_id"
    DATA_URL="$file_url"

EOF
    ;;

  rclone)
    command -v rclone >/dev/null || die "rclone is not installed: https://rclone.org/install/ (then run 'rclone config')"
    info "uploading to $RCLONE_REMOTE"
    rclone copy "$BUNDLE_ZIP" "$RCLONE_REMOTE/" --progress
    rclone copy "$BUNDLE_SHA" "$RCLONE_REMOTE/" --progress
    url="$(rclone link "$RCLONE_REMOTE/$(basename "$BUNDLE_ZIP")" 2>/dev/null || true)"
    if [[ -n "$url" ]]; then info "public link: $url"; else
      warn "no link created; share the file manually and put the link in DATA_URL"
    fi
    cat <<EOF

Paste these into data_bundle.env so a fresh clone can fetch the data:

    BUNDLE_BACKEND="rclone"
    RCLONE_REMOTE="$RCLONE_REMOTE"
    DATA_URL="$url"

EOF
    ;;

  *) die "unknown backend '$BUNDLE_BACKEND' (expected zenodo or rclone)" ;;
esac
