from hoopgn.entities.entity import Entity
from hoopgn.properties.property import Property
from hoopgn.properties.default.v2.domain import DomainConfig
from hoopgn.properties.default.v2.position import PositionConfig
from hoopgn.properties.default.v2.rotation import RotationConfig
from hoopgn.properties.default.v2.state import StateConfig


red = Entity.Config(
    sig=Entity.Signature(
        label="red",
        id=0,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="block_red_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="block_red_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="block_red_scalar",
            id=2,
        ),
    ),
)
blue = Entity.Config(
    sig=Entity.Signature(
        label="blue",
        id=1,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="block_blue_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="block_blue_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="block_blue_scalar",
            id=2,
        ),
    ),
)
pink = Entity.Config(
    sig=Entity.Signature(
        label="pink",
        id=2,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="block_pink_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="block_pink_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="block_pink_scalar",
            id=2,
        ),
    ),
)
slider = Entity.Config(
    sig=Entity.Signature(
        label="slider",
        id=3,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="slide_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="slide_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="slide_scalar",
            id=2,
        ),
    ),
)
drawer = Entity.Config(
    sig=Entity.Signature(
        label="drawer",
        id=4,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="drawer_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="drawer_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="drawer_scalar",
            id=2,
        ),
    ),
)
button = Entity.Config(
    sig=Entity.Signature(
        label="button",
        id=5,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="button_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="button_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="button_scalar",
            id=2,
        ),
    ),
)
led = Entity.Config(
    sig=Entity.Signature(
        label="led",
        id=6,
    ),
    domain=DomainConfig(
        sig=Property.Signature(
            label="domain",
            id=0,
        ),
    ),
    position=PositionConfig(
        sig=Property.Signature(
            label="led_position",
            id=0,
        ),
    ),
    rotation=RotationConfig(
        sig=Property.Signature(
            label="led_rotation",
            id=1,
        ),
    ),
    state=StateConfig(
        sig=Property.Signature(
            label="button_scalar",
            id=2,
        ),
    ),
)
